version: '3.8'

services:
  db:
    image: mysql:8.4.4
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: K1m_D0kja20KAJ2M
      MYSQL_DATABASE: MUSIC
    ports:
      - "3306:3306"
    networks:
      - devops4-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 50s
      timeout: 30s
      retries: 20

  backend:
    build:
      context: ./backend 
      dockerfile: Dockerfile
    container_name: devops4-backend
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: K1m_D0kja20KAJ2M
      DB_NAME: MUSIC
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - devops4-network

  frontend:
    build:
      context: ./topmusic 
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - devops4-network

networks:
  devops4-network:
    driver: bridge