version: '3.8'

services:
  db:
    image: mysql:8.4.4
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: K1m_D0kja20KAJ2M
      MYSQL_DATABASE: MUSIC
    ports:
      - "3306:3306"
    networks:
      - devops4-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 50s
      timeout: 30s
      retries: 20
      
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml  # Asegúrate de crear esta carpeta
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    depends_on:
      - backend
    networks:
      - devops4-network

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3001:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - devops4-network

  backend:
    build:
      context: ./backend 
      dockerfile: Dockerfile
    container_name: devops4-backend
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: K1m_D0kja20KAJ2M
      DB_NAME: MUSIC
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend/logs:/app/logs
    networks:
      - devops4-network

  frontend:
    build:
      context: ./topmusic 
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - devops4-network

networks:
  devops4-network:
    driver: bridge

volumes:
  grafana-storage: