version: '3.8'

services:
  db:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: "K1m_D0kja20KAJ2M"
      MYSQL_DATABASE: "MUSIC"
    ports:
      - "3307:3306"
    networks:
      - my_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: "K1m_D0kja20KAJ2M"
      DB_NAME: MUSIC
    ports:
      - "8000:8000"
    networks:
      - my_network

  frontend:
    build:
      context: ./topmusic
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - my_network

networks:
  my_network:
    driver: bridge