global:
  scrape_interval: 15s  
  evaluation_interval: 15s  

scrape_configs:
  - job_name: "fastapi-backend"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["backend:8000"] 
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: "backend"

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"] 