name: Python Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest 
    
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_HOST: localhost
          MYSQL_USER: root
          MYSQL_ROOT_PASSWORD: K1m_D0kja20KAJ2M
          MYSQL_DATABASE: MUSIC
        ports:
          - 3306:3306

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        cd tests
        pytest test_api.py -v --junitxml=../pytest-report.xml

    - name: Upload test results
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: pytest-report.xml

