name: Snyk Security Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  snyk:
    name: Escaneo de seguridad con Snyk
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Node
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 22.14

      - name: Instalar Snyk CLI
        run: npm install -g snyk

      - name: Instalar dependencias de Python
        run: pip install -r backend/requirements.txt

      - name: Escanear todas las carpetas detectables
        env: 
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk test --all-projects --severity-threshold=medium

      - name: Generar reporte en JSON
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk test --all-projects --json > snyk-report.json

      - name: Subir artefacto con el reporte
        uses: actions/download-artifact@v4
        with:
          name: snyk-report
          path: snyk-report.json
